GameJunkies.WebMVC/Controllers/ConsoleController.cs
using GameJunkies.Contracts;
using GameJunkies.Models.Console;
using GameJunkies.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GameJunkies.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ConsoleController : Controller
    {
        private readonly IConsoleService _consoleService;

        public ConsoleController(IConsoleService consoleService)
        {
            _consoleService = consoleService;
        }
        // GET: Console
        public ActionResult Index()
        {
            if (TempData["list"] != null)
            {
                return View(TempData["list"]);
            }
            //var service = new ConsoleService();
            var model = _consoleService.GetConsoles();
            return View(model);
        }
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ConsoleCreate model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            //var service = new ConsoleService();

            if (_consoleService.CreateConsole(model))
            {
                TempData["SaveResult"] = "Your console was added.";
                return RedirectToAction("Index");
            }
            ModelState.AddModelError("", "Console could not be added.");
            return View(model);

        }
        public ActionResult Details(int id)
        {
          //  var service = new ConsoleService();
            var model = _consoleService.GetConsoleById(id);
            if (model == null)
            {
                return RedirectToAction("Index");
            }
            return View(model);
        }
        public ActionResult Edit(int id)
        {
           // var service = new ConsoleService();
            var detail = _consoleService.GetConsoleById(id);
            var model = new ConsoleEdit() 
            {
                ConsoleId = detail.Id,
                Name = detail.Name,
                Description = detail.Description,
                Brand = detail.Brand,
                Price = detail.Price,
                ReleaseDate = detail.ReleaseDate
            };
            return View(model);

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, ConsoleEdit model)
        {
            if (!ModelState.IsValid) return View(model);
            if (model.ConsoleId != id)
            {
                ModelState.AddModelError("", "Id Mismatch");
                return View(model);
            }
           // var service = new ConsoleService();
            if (_consoleService.UpdateConsole(model))
            {
                TempData["SaveResult"] = "The console was updated.";
                return RedirectToAction("Index");
            }
            ModelState.AddModelError("", "Console could not be updated.");
            return View(model);
        }
        [ActionName("Delete")]
        public ActionResult Delete(int id)
        {
         //   var service = new ConsoleService();
            var model = _consoleService.GetConsoleById(id);

            return View(model);
        }
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeletePost(int id)
        {

           // var service = new ConsoleService();
            _consoleService.DeleteConsole(id);
            TempData["SaveResult"] = "Your console was deleted";
            return RedirectToAction("Index");
        }
    }
}

GameJunkies.WebMVC/Controllers/GameController.cs
using GameJunkies.Contracts;
using GameJunkies.Models.Console;
using GameJunkies.Models.ConsoleGame;
using GameJunkies.Models.Game;
using GameJunkies.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace GameJunkies.Controllers
{
    [Authorize(Roles = "Admin")]
    public class GameController : Controller
    {
        private readonly IGameService _gameService;
        private readonly IConsoleGameService _consoleGameService;

        public GameController(IGameService gameService, IConsoleGameService consoleGameService)
        {
            _gameService = gameService;
            _consoleGameService = consoleGameService;
        }
        // GET: Game
        public ActionResult Index()
        {
            if (TempData["list"]!=null)
            {
                return View(TempData["list"]);
            }
            //var service = new GameService();
            var model =_gameService.GetGames();
            return View(model);
        }
        
        public ActionResult Random()
        {
            //var service = new GameService();
            var request = _gameService.RandomGames();
            var model = request.Result;
            return View(model);
        }
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(GameCreate model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            //var service = new GameService();

            if (_gameService.CreateGame(model)){
                TempData["SaveResult"] = "Your game was added.";
                return RedirectToAction("Index");
            }
            ModelState.AddModelError("", "Game could not be added.");
            return View(model);
            
        }
        public ActionResult Details(int id)
        {
           // var service = new GameService();
            var model = _gameService.GetGameById(id);
            if(model == null)
            {
                return RedirectToAction("Index");
            }
            return View(model);
        }
        public ActionResult Edit(int id)
        {
           // var service = new GameService();
            var model = _gameService.GetGameEditById(id);
            return View(model);
            
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, GameEdit model)
        {
            if (!ModelState.IsValid) return View(model);
            if(model.GameId != id)
            {
                ModelState.AddModelError("", "Id Mismatch");
                return View(model);
            }
           // var service = new GameService();
            if (_gameService.UpdateGame(model))
            {
                TempData["SaveResult"] = "The game was updated.";
                return RedirectToAction("Index");
            }
            ModelState.AddModelError("", "Game could not be updated.");
            return View(model);
        }
        [ActionName("Delete")]
        public ActionResult Delete(int id)
        {
            //var service = new GameService();
            var model = _gameService.GetGameById(id);
            
            return View(model);
        }
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeletePost(int id)
        {
            
            //var service = new GameService();
            _gameService.DeleteGame(id);
            TempData["SaveResult"] = "Your game was deleted";
            return RedirectToAction("Index");
        }
        public ActionResult ConsoleLink(int id)
        {
            //var service = new ConsoleGameService();
            var model = _consoleGameService.GetCreateLink(id);
            
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ConsoleLink(ConsoleGamesCreates model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            //var service = new ConsoleGameService();

            if (_consoleGameService.CreateConsoleGames(model))
            {
                TempData["SaveResult"] = "Your game was linked.";
                return RedirectToAction("Index");
            }
            ModelState.AddModelError("", "Game could not be linked.");
            return View(model);

        }
    }
}

GameJunkies.WebMVC/Controllers/GenreController.cs
using GameJunkies.Contracts;
using GameJunkies.Models.Genre;
using GameJunkies.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GameJunkies.Controllers
{
    [Authorize(Roles = "Admin")]
    public class GenreController : Controller
    {
        // GET: Genre
        private readonly IGenreService _genreService;

        public GenreController(IGenreService genreService)
        {
            _genreService = genreService;
        }
        public ActionResult Index()
        {
            if (TempData["list"] != null)
            {
                return View(TempData["list"]);
            }
           // var service = new GenreService();
            var model = _genreService.GetGenres();
            return View(model);
        }
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(GenreCreate model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            //var service = new GenreService();

            if (_genreService.CreateGenre(model))
            {
                TempData["SaveResult"] = "Your Genre was added.";
                return RedirectToAction("Index");
            }
            ModelState.AddModelError("", "Genre could not be added.");
            return View(model);

        }
        public ActionResult Details(int id)
        {
           // var service = new GenreService();
            var model = _genreService.GetGenreById(id);
            if (model == null)
            {
                return RedirectToAction("Index");
            }
            return View(model);
        }
        public ActionResult Edit(int id)
        {
           // var service = new GenreService();
            var detail = _genreService.GetGenreById(id);
            var model = new GenreEdit()
            {
               Id = detail.Id,
                Name = detail.Name,
                Description = detail.Description
            };
            return View(model);

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, GenreEdit model)
        {
            if (!ModelState.IsValid) return View(model);
            if (model.Id != id)
            {
                ModelState.AddModelError("", "Id Mismatch");
                return View(model);
            }
           // var service = new GenreService();
            if (_genreService.UpdateGenre(model))
            {
                TempData["SaveResult"] = "The genre was updated.";
                return RedirectToAction("Index");
            }
            ModelState.AddModelError("", "Genre could not be updated.");
            return View(model);
        }
        [ActionName("Delete")]
        public ActionResult Delete(int id)
        {
            //var service = new GenreService();
            var model = _genreService.GetGenreById(id);

            return View(model);
        }
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeletePost(int id)
        {

           // var service = new GenreService();
            _genreService.DeleteGenre(id);
            TempData["SaveResult"] = "Your genre was deleted";
            return RedirectToAction("Index");
        }
    }
}

GameJunkies.WebMVC/Controllers/RetailerController.cs
using GameJunkies.Contracts;
using GameJunkies.Models.Retailer;
using GameJunkies.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GameJunkies.Controllers
{
    [Authorize(Roles = "Admin")]
    public class RetailerController : Controller
    {
        private readonly IRetailerService _retailerService;
        public RetailerController (IRetailerService retailerService)
        {
            _retailerService = retailerService;
        }
        // GET: Retailer
        public ActionResult Index()

        {
            if (TempData["list"] != null)
            {
                return View(TempData["list"]);
            }
          //  var service = new RetailerService();
            var model = _retailerService.GetRetailers();
            return View(model);
        }
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(RetailerCreate model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

           // var service = new RetailerService();

            if (_retailerService.CreateRetailer(model))
            {
                TempData["SaveResult"] = "Your retailer was added.";
                return RedirectToAction("Index");
            }
            ModelState.AddModelError("", "Retailer could not be added.");
            return View(model);

        }
        public ActionResult Details(int id)
        {
         //   var service = new RetailerService();
            var model = _retailerService.GetRetailerById(id);
            if (model == null)
            {
                return RedirectToAction("Index");
            }
            return View(model);
        }
        public ActionResult Edit(int id)
        {
           // var service = new RetailerService();
            var detail = _retailerService.GetRetailerById(id);
            var model = new RetailerEdit()
            {
                Id = detail.RetailerId,
                Name = detail.Name,
                WebsiteUrl = detail.WebsiteUrl,
                HasPhysicalLocations = detail.HasPhysicalLocations
            };
            return View(model);

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, RetailerEdit model)
        {
            if (!ModelState.IsValid) return View(model);
            if (model.Id != id)
            {
                ModelState.AddModelError("", "Id Mismatch");
                return View(model);
            }
            //var service = new RetailerService();
            if (_retailerService.UpdateRetailer(model))
            {
                TempData["SaveResult"] = "The retailer was updated.";
                return RedirectToAction("Index");
            }
            ModelState.AddModelError("", "Retailer could not be updated.");
            return View(model);
        }
        [ActionName("Delete")]
        public ActionResult Delete(int id)
        {
            //var service = new RetailerService();
            var model = _retailerService.GetRetailerById(id);

            return View(model);
        }
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeletePost(int id)
        {

            //  var service = new RetailerService();
            _retailerService.DeleteRetailer(id);
            TempData["SaveResult"] = "Your retailer was deleted";
            return RedirectToAction("Index");
        }
    }
}

GameJunkies.WebMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - GameJunkies</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
   
    

</head>
<body class="">


    <nav class="navbar navbar-expand-lg navbar-light fixed-top" style="background-color: #99a2ad;">
        <a class="navbar-brand" href="#">GameJunkies</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse justify-content-start" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">

                    @Html.ActionLink("Home", "Index", "Home", routeValues: null, new { @class = "nav-link text-dark" })
                </li>
                <li class="nav-item" src =>
                    @Html.ActionLink("About", "About", "Home", routeValues: null, new { @class = "nav-link text-dark" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink("Contact", "Contact", "Home", routeValues: null, new { @class = "nav-link text-dark" })
                </li>
                @if (User.IsInRole("Admin"))
                {
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle text-dark" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Repos
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            @Html.ActionLink("Games", "Index", "Game", routeValues: null, new { @class = "dropdown-item" })
                            @Html.ActionLink("Consoles", "Index", "Console", routeValues: null, new { @class = "dropdown-item" })
                            @Html.ActionLink("Retailers", "Index", "Retailer", routeValues: null, new { @class = "dropdown-item" })
                            @Html.ActionLink("Publishers", "Index", "Publisher", routeValues: null, new { @class = "dropdown-item" })
                            @Html.ActionLink("Developers", "Index", "Developer", routeValues: null, new { @class = "dropdown-item" })
                            @Html.ActionLink("Genres", "Index", "Genre", routeValues: null, new { @class = "dropdown-item" })

                        </div>
                    </li>
                }


            </ul>
            <form class="form-inline">

                <label class="my-1 mr-2" for="inlineFormCustomSelectPref">Database</label>
                <select class="custom-select my-1 mr-sm-2" id="inlineFormCustomSelectPref">
                    <option value="Game">Games</option>
                    <option value="Console">Consoles</option>
                    <option value="Genre">Genres</option>
                    <option value="Retailer">Retailers</option>
                    <option value="Publisher">Publishers</option>
                    <option value="Developer">Developers</option>
                </select>

                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" id="searchText">
                <button class="btn btn-outline-primary my-2 my-sm-0" type="button" id="universalSearch">Search</button>
            </form>
        </div>
        @Html.Partial("_LoginPartial")
    </nav>
  

    <div class="container body-content" style="padding-top:3rem;">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Connor Braeger</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/custom")
    @RenderSection("scripts", required: false)
</body>
</html>